- label: 'Getting Started'
  link: '/'
- label: 'Api Overview'
  link: '/api'
- label: 'React Native'
  link: '/react-native'
  items: 
    - label: 'RNBluetoothClassic'
      link: '/react-native/rn-bluetooth-classic'
    - label: 'RNBluetoothDevice'
      link: '/react-native/rn-bluetooth-device'
- label: 'Android APIs'
  link: '/android'
  items:
    - label: 'Getting Started'
      link: '/android'
    - label: 'RN Bluetooth Classic Package'
      link: '/android/rn-bluetooth-classic-package'
    - label: 'RN Bluetooth Classic Module'
      link: '/android/rn-bluetooth-classic-module'
    - label: 'Connection Acceptor'
      link: '/android/connection-acceptor'
    - label: 'Connection Connector'
      link: '/android/connection-connector'
    - label: 'Device Connection'
      link: '/android/device-connection'
- label: 'IOS APIs'
  link: '/ios'
  items:
    - label: 'Getting Started'
      link: '/ios'
- label: 'Guides'
  link: '/guides'
  items:
    - label: 'Using with Expo'
      link: '/guides/using-with-expo'
    - label: 'Hex Encoding/Decoding'
      link: '/guides/hex-encoding-decoding'      