declare enum BluetoothError {
    BLUETOOTH_NOT_ACCEPTING = "BLUETOOTH_NOT_ACCEPTING",
    BLUETOOTH_IN_ACCEPTING = "BLUETOOTH_IN_ACCEPTING",
    BLUETOOTH_IN_DISCOVERY = "BLUETOOTH_IN_DISCOVERY",
    ALREADY_CONNECTED = "ALREADY_CONNECTED",
    ALREADY_CONNECTING = "ALREADY_CONNECTING",
    NOT_CURRENTLY_CONNECTED = "NOT_CURRENTLY_CONNECTED",
    BONDING_UNAVAILABLE_API = "BONDING_UNAVAILABLE_API",
    DISCOVERY_FAILED = "DISCOVERY_FAILED",
    WRITE_FAILED = "WRITE_FAILED",
    READ_FAILED = "READ_FAILED",
    ACCEPTING_CANCELLED = "ACCEPTING_CANCELLED",
    CONNECTION_FAILED = "CONNECTION_FAILED",
    CONNECTION_LOST = "CONNECTION_LOST",
    PAIRING_FAILED = "PAIRING_FAILED"
}
export default BluetoothError;
