enum BluetoothEvents {
    BLUETOOTH_ENABLED = "BLUETOOTH_ENABLED",
    BLUETOOTH_DISABLED = "BLUETOOTH_DISABLED",
    DEVICE_CONNECTED = "DEVICE_CONNECTED",
    DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED",
    DEVICE_READ = "DEVICE_READ",
    ERROR = "ERROR"
};

export default BluetoothEvents;